# Antioxidant level score out of 5 stars
antioxidant_score = {
    "apple": 3,
    "banana": 2,
    "beetroot": 5,
    "bell pepper": 4,
    "cabbage": 3,
    "capsicum": 3,
    "carrot": 3,
    "cauliflower": 3,
    "chilli pepper": 4,
    "corn": 2,
    "cucumber": 1,
    "eggplant": 4,
    "garlic": 5,
    "ginger": 5,
    "grapes": 4,
    "jalepeno": 3,
    "kiwi": 4,
    "lemon": 3,
    "lettuce": 2,
    "mango": 4,
    "onion": 3,
    "orange": 3,
    "paprika": 4,
    "pear": 3,
    "peas": 3,
    "pineapple": 3,
    "pomegranate": 5,
    "potato": 1,
    "raddish": 2,
    "soy beans": 3,
    "spinach": 5,
    "sweetcorn": 2,
    "sweetpotato": 4,
    "tomato": 3,
    "turnip": 2,
    "watermelon": 2
}


nutrition_info = {
    'apple': {'calories': 52, 'carbs': 14, 'protein': 0.3, 'fat': 0.2},
    'banana': {'calories': 89, 'carbs': 23, 'protein': 1.1, 'fat': 0.3},
    'beetroot': {'calories': 43, 'carbs': 10, 'protein': 1.6, 'fat': 0.2},
    'bell pepper': {'calories': 31, 'carbs': 6, 'protein': 1, 'fat': 0.3},
    'cabbage': {'calories': 25, 'carbs': 6, 'protein': 1.3, 'fat': 0.1},
    'capsicum': {'calories': 26, 'carbs': 6, 'protein': 1, 'fat': 0.2},
    'carrot': {'calories': 41, 'carbs': 10, 'protein': 0.9, 'fat': 0.2},
    'cauliflower': {'calories': 25, 'carbs': 5, 'protein': 1.9, 'fat': 0.3},
    'chilli pepper': {'calories': 40, 'carbs': 9, 'protein': 2, 'fat': 0.4},
    'corn': {'calories': 86, 'carbs': 19, 'protein': 3.2, 'fat': 1.2},
    'cucumber': {'calories': 16, 'carbs': 4, 'protein': 0.7, 'fat': 0.1},
    'eggplant': {'calories': 25, 'carbs': 6, 'protein': 1, 'fat': 0.2},
    'garlic': {'calories': 149, 'carbs': 33, 'protein': 6.4, 'fat': 0.5},
    'ginger': {'calories': 80, 'carbs': 18, 'protein': 1.8, 'fat': 0.8},
    'grapes': {'calories': 69, 'carbs': 18, 'protein': 0.7, 'fat': 0.2},
    'jalepeno': {'calories': 29, 'carbs': 6.5, 'protein': 0.9, 'fat': 0.4},
    'kiwi': {'calories': 61, 'carbs': 15, 'protein': 1.1, 'fat': 0.5},
    'lemon': {'calories': 29, 'carbs': 9, 'protein': 1.1, 'fat': 0.3},
    'lettuce': {'calories': 15, 'carbs': 2.9, 'protein': 1.4, 'fat': 0.2},
    'mango': {'calories': 60, 'carbs': 15, 'protein': 0.8, 'fat': 0.4},
    'onion': {'calories': 40, 'carbs': 9, 'protein': 1.1, 'fat': 0.1},
    'orange': {'calories': 47, 'carbs': 12, 'protein': 0.9, 'fat': 0.1},
    'paprika': {'calories': 282, 'carbs': 54, 'protein': 14.1, 'fat': 12.9},
    'pear': {'calories': 57, 'carbs': 15, 'protein': 0.4, 'fat': 0.1},
    'peas': {'calories': 81, 'carbs': 14, 'protein': 5, 'fat': 0.4},
    'pineapple': {'calories': 50, 'carbs': 13, 'protein': 0.5, 'fat': 0.1},
    'pomegranate': {'calories': 83, 'carbs': 19, 'protein': 1.7, 'fat': 1.2},
    'potato': {'calories': 77, 'carbs': 17, 'protein': 2, 'fat': 0.1},
    'raddish': {'calories': 16, 'carbs': 3.4, 'protein': 0.7, 'fat': 0.1},
    'soy beans': {'calories': 173, 'carbs': 9.9, 'protein': 16.6, 'fat': 9},
    'spinach': {'calories': 23, 'carbs': 3.6, 'protein': 2.9, 'fat': 0.4},
    'sweetcorn': {'calories': 86, 'carbs': 19, 'protein': 3.2, 'fat': 1.2},
    'sweetpotato': {'calories': 86, 'carbs': 20, 'protein': 1.6, 'fat': 0.1},
    'tomato': {'calories': 18, 'carbs': 3.9, 'protein': 0.9, 'fat': 0.2},
    'turnip': {'calories': 28, 'carbs': 6.4, 'protein': 0.9, 'fat': 0.1},
    'watermelon': {'calories': 30, 'carbs': 8, 'protein': 0.6, 'fat': 0.2}
}

diet_notes = {
    'apple': "Good source of fiber and vitamin C. Generally hypoallergenic.",
    'banana': "High in potassium. Avoid if you have latex-fruit syndrome allergy.",
    'beetroot': "Rich in folate and nitrates, good for blood pressure regulation.",
    'bell pepper': "Excellent source of vitamin C and antioxidants.",
    'capsicum': "Similar to bell pepper; rich in vitamins A and C.",
    'carrot': "High in beta-carotene, promotes good vision.",
    'cauliflower': "Good source of fiber and vitamin C, low in calories.",
    'chilli pepper': "Contains capsaicin; may irritate sensitive stomachs.",
    'corn': "High in fiber and carbohydrates; contains antioxidants.",
    'cucumber': "Hydrating vegetable, mostly water content.",
    'eggplant': "Contains antioxidants and fiber; low calorie.",
    'garlic': "Known for immune-boosting properties; can cause odor.",
    'ginger': "Used for nausea relief and anti-inflammatory benefits.",
    'grapes': "Contains antioxidants and resveratrol, heart-healthy.",
    'jalepeno': "Spicy pepper with capsaicin; may cause irritation in sensitive individuals.",
    'kiwi': "High in vitamin C and fiber, may help digestion.",
    'lemon': "Rich in vitamin C; acidic and may cause sensitivity in some.",
    'lettuce': "Low calorie and hydrating; good source of fiber.",
    'mango': "High in vitamin A and sugar content; eat in moderation if diabetic.",
    'onion': "Contains antioxidants; may cause digestive discomfort for some.",
    'orange': "Excellent source of vitamin C and hydration.",
    'paprika': "Mild pepper, source of antioxidants and vitamin A.",
    'pear': "High in fiber and vitamin C; gentle on the stomach.",
    'peas': "Good source of plant protein and fiber.",
    'pineapple': "Contains bromelain, good for digestion but can irritate mouth.",
    'pomegranate': "Rich in antioxidants and vitamin C.",
    'potato': "High in starch and carbs; choose cooking method wisely.",
    'raddish': "Low calorie; may aid digestion and detoxification.",
    'soy beans': "High in protein and isoflavones; beneficial for heart health.",
    'spinach': "Rich in iron and calcium; contains oxalates that may affect some people.",
    'sweetcorn': "Sweet variety of corn; high in fiber and carbohydrates.",
    'sweetpotato': "Rich in beta-carotene and fiber; lower glycemic index than potato.",
    'tomato': "Contains lycopene, good for heart health; may cause acid reflux.",
    'turnip': "Low calorie root vegetable; contains fiber and vitamin C.",
    'watermelon': "Hydrating fruit with antioxidants; low calorie.",
}


recipe_suggestions = {
    'apple': "Great for pies, sauces, or eaten fresh as a snack.",
    'banana': "Perfect for smoothies, baking (banana bread), or as a snack.",
    'beetroot': "Use in salads, roasted as a side dish, or in smoothies.",
    'bell pepper': "Add to stir-fries, salads, or stuff with cheese and bake.",
    'cabbage': "Use in coleslaw, soups, or sautéed as a side.",
    'carrot': "Great raw in salads, roasted, or in stews and soups.",
    'cauliflower': "Use roasted, in curries, or as cauliflower rice.",
    'chilli pepper': "Add heat to dishes, sauces, or salsas.",
    'corn': "Grill and eat on the cob, use in salads or soups.",
    'cucumber': "Perfect in salads, sandwiches, or as pickles.",
    'eggplant': "Grill, roast, or use in stews and dips like baba ganoush.",
    'garlic': "Use as seasoning in almost any savory dish.",
    'ginger': "Great in teas, marinades, and baked goods.",
    'grapes': "Eat fresh, freeze for snacks, or use in salads.",
    'kiwi': "Eat fresh, add to fruit salads, or smoothies.",
    'lemon': "Use juice for dressings, drinks, or marinades.",
    'lettuce': "Use fresh in salads or sandwiches.",
    'mango': "Eat fresh, in smoothies, salsas, or desserts.",
    'onion': "Use in almost all savory cooking for flavor.",
    'orange': "Eat fresh, juice, or use zest in cooking and baking.",
    'paprika': "Use in sauces, salads, or as a spice in cooking.",
    'pear': "Eat fresh, bake in desserts, or add to salads.",
    'peas': "Use fresh or frozen in soups, stews, or salads.",
    'pineapple': "Eat fresh, grill, use in desserts or savory dishes.",
    'pomegranate': "Add seeds to salads, yogurt, or desserts.",
    'potato': "Bake, mash, fry, or roast.",
    'raddish': "Eat fresh in salads or as a garnish.",
    'soy beans': "Use cooked in stir-fries, salads, or make tofu.",
    'spinach': "Use fresh in salads, smoothies, or sauté as a side.",
    'sweetcorn': "Grill or boil and eat on the cob, or use kernels in dishes.",
    'sweetpotato': "Bake, roast, mash, or use in soups.",
    'tomato': "Use fresh in salads, sauces, or cooked in stews.",
    'turnip': "Roast, mash, or use in stews and soups.",
    'watermelon': "Eat fresh, in fruit salads, or as juice."
}

calorie_info = {
    # Fruits and veggies per 100g
    'apple': 52,
    'banana': 89,
    'beetroot': 43,
    'bell pepper': 20,
    'cabbage': 25,
    'capsicum': 20,
    'carrot': 41,
    'cauliflower': 25,
    'chilli pepper': 40,
    'corn': 86,
    'cucumber': 16,
    'eggplant': 25,
    'garlic': 149,
    'ginger': 80,
    'grapes': 69,
    'jalepeno': 29,
    'kiwi': 61,
    'lemon': 29,
    'lettuce': 15,
    'mango': 60,
    'onion': 40,
    'orange': 47,
    'paprika': 282,
    'pear': 57,
    'peas': 81,
    'pineapple': 50,
    'pomegranate': 83,
    'potato': 77,
    'raddish': 16,
    'soy beans': 173,
    'spinach': 23,
    'sweetcorn': 86,
    'sweetpotato': 86,
    'tomato': 18,
    'turnip': 28,
    'watermelon': 30,

    # Common snacks per typical serving size
    'potato chips (30g)': 160,
    'chocolate bar (45g)': 230,
    'cookie (30g)': 150,
    'popcorn (20g)': 90,
    'granola bar (40g)': 180
}
